name = 'elmozzacom'
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[assets]
directory = "./static"

[[d1_databases]]
binding = "DB"
database_name = "elmozza-db"
# Replace with your Cloudflare D1 database ID
database_id = "75491b81-a886-41cf-80e7-66156befcd4e"
