name = "elmozza"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./static"

[[d1_databases]]
binding = "DB"
database_name = "elmozza-db"
# Replace with your Cloudflare D1 database ID
database_id = "YOUR_D1_DATABASE_ID"
